require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarparksController do

  # This should return the minimal set of attributes required to create a valid
  # Carpark. As you add validations to Carpark, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "status" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarparksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all carparks as @carparks" do
      carpark = Carpark.create! valid_attributes
      get :index, {}, valid_session
      assigns(:carparks).should eq([carpark])
    end
  end

  describe "GET show" do
    it "assigns the requested carpark as @carpark" do
      carpark = Carpark.create! valid_attributes
      get :show, {:id => carpark.to_param}, valid_session
      assigns(:carpark).should eq(carpark)
    end
  end

  describe "GET new" do
    it "assigns a new carpark as @carpark" do
      get :new, {}, valid_session
      assigns(:carpark).should be_a_new(Carpark)
    end
  end

  describe "GET edit" do
    it "assigns the requested carpark as @carpark" do
      carpark = Carpark.create! valid_attributes
      get :edit, {:id => carpark.to_param}, valid_session
      assigns(:carpark).should eq(carpark)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Carpark" do
        expect {
          post :create, {:carpark => valid_attributes}, valid_session
        }.to change(Carpark, :count).by(1)
      end

      it "assigns a newly created carpark as @carpark" do
        post :create, {:carpark => valid_attributes}, valid_session
        assigns(:carpark).should be_a(Carpark)
        assigns(:carpark).should be_persisted
      end

      it "redirects to the created carpark" do
        post :create, {:carpark => valid_attributes}, valid_session
        response.should redirect_to(Carpark.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved carpark as @carpark" do
        # Trigger the behavior that occurs when invalid params are submitted
        Carpark.any_instance.stub(:save).and_return(false)
        post :create, {:carpark => { "status" => "invalid value" }}, valid_session
        assigns(:carpark).should be_a_new(Carpark)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Carpark.any_instance.stub(:save).and_return(false)
        post :create, {:carpark => { "status" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested carpark" do
        carpark = Carpark.create! valid_attributes
        # Assuming there are no other carparks in the database, this
        # specifies that the Carpark created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Carpark.any_instance.should_receive(:update).with({ "status" => "MyString" })
        put :update, {:id => carpark.to_param, :carpark => { "status" => "MyString" }}, valid_session
      end

      it "assigns the requested carpark as @carpark" do
        carpark = Carpark.create! valid_attributes
        put :update, {:id => carpark.to_param, :carpark => valid_attributes}, valid_session
        assigns(:carpark).should eq(carpark)
      end

      it "redirects to the carpark" do
        carpark = Carpark.create! valid_attributes
        put :update, {:id => carpark.to_param, :carpark => valid_attributes}, valid_session
        response.should redirect_to(carpark)
      end
    end

    describe "with invalid params" do
      it "assigns the carpark as @carpark" do
        carpark = Carpark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Carpark.any_instance.stub(:save).and_return(false)
        put :update, {:id => carpark.to_param, :carpark => { "status" => "invalid value" }}, valid_session
        assigns(:carpark).should eq(carpark)
      end

      it "re-renders the 'edit' template" do
        carpark = Carpark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Carpark.any_instance.stub(:save).and_return(false)
        put :update, {:id => carpark.to_param, :carpark => { "status" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested carpark" do
      carpark = Carpark.create! valid_attributes
      expect {
        delete :destroy, {:id => carpark.to_param}, valid_session
      }.to change(Carpark, :count).by(-1)
    end

    it "redirects to the carparks list" do
      carpark = Carpark.create! valid_attributes
      delete :destroy, {:id => carpark.to_param}, valid_session
      response.should redirect_to(carparks_url)
    end
  end

end
